### ISSUE TITLE
great stuff !

### ISSUE THREAD

**Issue by aktxyz** [petrbrouzda/VictronRemoteDisplay#1]
This is fantastic, the MQTT stuff, the ESP32 approach, etc.
I am working on some tank monitoring setup using ESP32.

I have recently installed 3 victron smart chargers and can check status using the victron connect app.

What I really want is for the status on to be available on my local wifi ... have you ever played around with figuring out victron connect bluetooth and trying to get access to that info?

**Comment by petrbrouzda** [comment]
I don't use bluetooth interface, because Cerbo GX contains all the information contained on bluetooth advertising.
But there are projects that do so:
- stand alone application - https://github.com/hoberman/Victron_BLE_Advertising_example
- HomeAssistant integration (this seems to be better way) - https://github.com/Fabian-Schmidt/esphome-victron_ble
-

**Comment by petrbrouzda** [comment]
I don't use bluetooth interface, because Cerbo GX contains all the information contained on bluetooth advertising.
But there are projects that do so:
- stand alone application - https://github.com/hoberman/Victron_BLE_Advertising_example
- HomeAssistant integration (this seems to be better way) - https://github.com/Fabian-Schmidt/esphome-victron_ble

**Comment by petrbrouzda** [comment]
I don't use bluetooth interface, because Cerbo GX contains all the information contained on bluetooth advertising.
But there are projects that do so:
- stand alone application - https://github.com/hoberman/Victron_BLE_Advertising_example
- HomeAssistant integration (this seems to be better way) - https://github.com/Fabian-Schmidt/esphome-victron_ble
